version: '3.8'

services:
  python-app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    restart: unless-stopped

  react-app:
    build: 
      context: ./social-space
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - python-app
    restart: unless-stopped
